[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
solc_version = '0.8.19'
fs_permissions = [{ access = "read", path = "./out"},{ access = "read-write", path = "./deployments"}]

[rpc_endpoints]
MAINNET = "${MAINNET_RPC_URL}"
ARBITRUM = "${ARBITRUM_RPC_URL}"
OPTIMISM = "${OPTIMISM_RPC_URL}"
LOCAL = "${LOCAL_RPC_URL}"

[invariant]
call_override = false  # Override calls
runs          = 1000    # The number of times to run the invariant tests
depth         = 1   # The number of calls to make in the invariant tests

[profile.no_revert.invariant]
fail_on_revert = false  

[profile.allow_revert.invariant]
fail_on_revert = true 


# See more config options https://github.com/foundry-rs/foundry/tree/master/config